[package]
name = "template_yarte"
version = "0.0.1"
authors = ["Juan Aguilar Santillana <mhpoin@gmail.com>"]
publish = false
edition = "2018"

workspace = ".."

[dependencies]
env_logger = "0.9"
yarte = { version = "0.15", features = ["html-min"]  }
ntex = { version = "0.5", features = ["tokio"] }

[build-dependencies.yarte_helpers]
version = "0.15.6"
default-features = false
features = ["config"]
