[package]
name = "template-askama"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.5", features = ["tokio"] }
askama = "0.11.0"

[build-dependencies]
askama = "0.11.0"
